name: Setup environment
description: Setup environment with Node.js, Deno and pnpm

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9
        run_install: false

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 22
        registry-url: 'https://registry.npmjs.org'
        cache: pnpm

    - name: Setup Deno
      uses: denoland/setup-deno@v2
      with:
        deno-version: v2.5.6

    - name: Install dependencies
      shell: bash
      run: pnpm install

    - name: Create library build cache
      id: library-build-cache
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/library/dist
        key: library-build-cache-${{ hashFiles('library/src/**/*.ts', '!library/src/**/*.test.ts', '!library/src/**/*.test-d.ts') }}

    - name: Build library
      if: steps.library-build-cache.outputs.cache-hit != 'true'
      shell: bash
      run: pnpm build
      working-directory: library

    - name: Create to-json-schema build cache
      id: to-json-schema-build-cache
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/packages/to-json-schema/dist
        key: to-json-schema-build-cache-${{ hashFiles('packages/to-json-schema/src/**/*.ts', '!packages/to-json-schema/src/**/*.test.ts') }}

    - name: Build to-json-schema
      if: steps.to-json-schema-build-cache.outputs.cache-hit != 'true'
      shell: bash
      run: pnpm build
      working-directory: packages/to-json-schema

    - name: Create zod-to-valibot build cache
      id: zod-to-valibot-build-cache
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/codemod/zod-to-valibot/dist
        key: zod-to-valibot-build-cache-${{ hashFiles('codemod/zod-to-valibot/src/**/*.ts', '!codemod/zod-to-valibot/src/**/*.test.ts') }}

    - name: Build zod-to-valibot
      if: steps.zod-to-valibot-build-cache.outputs.cache-hit != 'true'
      shell: bash
      run: pnpm build
      working-directory: codemod/zod-to-valibot
